// src/airNomadIngredients.ts

import { Ingredient } from './types';

export const airNomadIngredients: Ingredient[] = [
    // --- FRUIT ---
    { name: 'Apple', emoji: '🍎', rarity: 'Common', category: 'fruit', flavorProfile: 'sweet', isPlural: false, suitability: ['pie', 'bake', 'salad', 'juice'], description: 'A crisp, versatile fruit, often used in both pies and refreshing juices.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Flour': 8, "Monk's Honey": 5 } },
    { name: 'Banana', emoji: '🍌', rarity: 'Common', category: 'fruit', flavorProfile: 'sweet', isPlural: false, suitability: ['pie', 'bake', 'juice'], description: 'A soft, sweet fruit that provides quick energy for long meditation sessions.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Flour': 6, 'Vanilla': 5 } },
    { name: 'Moon Peach', emoji: '🍑', rarity: 'Rare', category: 'fruit', flavorProfile: 'sweet', isPlural: false, suitability: ['pie', 'salad', 'garnish'], description: 'A rare, mystical fruit said to bloom only under the full moon.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Vanilla': 7, 'Monk\'s Honey': 5 } },
    { name: 'Lychee Nuts', emoji: '🥭', rarity: 'Uncommon', category: 'fruit', flavorProfile: 'sweet', isPlural: true, suitability: ['pie', 'salad', 'juice', 'garnish'], description: 'Small, fragrant fruits with a delicate sweetness and floral aroma.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Monk\'s Honey': 5 } },
    { name: 'Mango', emoji: '🥭', rarity: 'Uncommon', category: 'fruit', flavorProfile: 'sweet', isPlural: false, suitability: ['pie', 'curry', 'salad', 'juice'], description: 'A tropical fruit with rich, sweet flesh perfect for both sweet and savory dishes.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Coconut': 7 } },
    { name: 'Coconut', emoji: '🥥', rarity: 'Uncommon', category: 'fruit', flavorProfile: 'sweet', isPlural: false, suitability: ['pie', 'bake', 'curry'], description: 'A versatile fruit providing both meat and milk for various culinary uses.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Mango': 7 } },
    { name: 'Plums', emoji: '🫐', rarity: 'Common', category: 'fruit', flavorProfile: 'sweet', isPlural: true, suitability: ['pie', 'bake', 'juice'], description: 'Juicy, tart fruits that are often preserved or baked into pastries.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Flour': 6 } },

    // --- VEGETABLES ---
    { name: 'Cabbage', emoji: '🥬', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: false, suitability: ['steam', 'stir-fry', 'curry', 'salad', 'dumpling'], description: 'A leafy green that forms the base of many hearty Air Nomad dishes.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Tofu': 7 } },
    { name: 'Carrot', emoji: '🥕', rarity: 'Common', category: 'vegetable', flavorProfile: 'sweet', isPlural: false, suitability: ['steam', 'stir-fry', 'curry', 'salad', 'dumpling', 'bake', 'juice'], description: 'A sweet root vegetable that adds color and crunch to meals.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Onion': 5 } },
    { name: 'Bean Sprouts', emoji: '🌱', rarity: 'Common', category: 'vegetable', flavorProfile: 'neutral', isPlural: true, suitability: ['steam', 'stir-fry', 'salad'], description: 'Tender, crisp sprouts that add a fresh, clean flavor.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Tofu': 4 } },
    { name: 'Onion', emoji: '🧅', rarity: 'Common', category: 'vegetable', flavorProfile: 'pungent', isPlural: false, suitability: ['stir-fry', 'curry', 'dumpling', 'bake', 'pie'], description: 'A foundational vegetable that adds savory depth to countless recipes.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Potato': 7, 'Carrot': 5 } },
    { name: 'Potato', emoji: '🥔', rarity: 'Common', category: 'vegetable', flavorProfile: 'neutral', isPlural: false, suitability: ['steam', 'curry', 'bake', 'pie'], description: 'A starchy, comforting staple grown in high-altitude temple gardens.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Onion': 7 } },
    { name: 'Tomato', emoji: '🍅', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: false, suitability: ['curry', 'salad', 'bake'], description: 'A juicy, bright vegetable used in sauces, salads, and baked dishes.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Onion': 5 } },
    { name: 'Pickles', emoji: '🥒', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: true, suitability: ['salad', 'garnish'], description: 'Cucumbers preserved in a tangy brine, adding a sharp kick to meals.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Peppers', emoji: '🌶️', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: true, suitability: ['steam', 'stir-fry', 'curry', 'salad'], description: 'A colorful vegetable that adds a mild, sweet heat.', nation: 'air-nomads', location: 'Air Temple' },

    // --- FUNGI ---
    { name: 'Oyster Mushrooms', emoji: '🍄', rarity: 'Common', category: 'fungi', flavorProfile: 'umami', isPlural: true, suitability: ['steam', 'stir-fry', 'curry', 'pie'], description: 'Delicate, fan-shaped mushrooms with a subtle, savory flavor.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Tofu': 5 } },
    { name: 'Shiitake Mushrooms', emoji: '🍄', rarity: 'Uncommon', category: 'fungi', flavorProfile: 'umami', isPlural: true, suitability: ['steam', 'stir-fry', 'curry', 'pie', 'dumpling'], description: 'Rich, meaty mushrooms prized for their deep umami flavor and medicinal properties.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Tofu': 6 } },

    // --- BASE ---
    { name: 'Light Vegetable Broth', emoji: '🥣', rarity: 'Common', category: 'base', flavorProfile: 'savory', isPlural: false, suitability: ['curry', 'steam'], description: 'A clear, savory broth made from mountain vegetables, used as a base for soups and stews.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Rice', emoji: '🍚', rarity: 'Common', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['steam', 'curry', 'stir-fry', 'salad', 'bake'], description: 'The staple grain of Air Nomad cuisine, symbolizing simplicity and sustenance.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Barley', emoji: '🌾', rarity: 'Common', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['steam', 'curry', 'bake'], description: 'A hearty grain that provides warmth and nourishment during cold mountain nights.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Flour', emoji: '🌾', rarity: 'Common', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['bake', 'pie', 'dumpling'], description: 'Finely milled grain used for baking breads, pies, and dumplings.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Apple': 8, 'Banana': 6, 'Plums': 6 } },
    { name: 'Mountain Noodles', emoji: '🍜', rarity: 'Common', category: 'base', flavorProfile: 'neutral', isPlural: true, suitability: ['steam', 'stir-fry', 'curry'], description: 'Simple, elegant noodles made from mountain spring water and flour.', nation: 'air-nomads', location: 'Air Temple' },

    // --- PROTEIN ---
    { name: 'Tofu', emoji: '⬜', rarity: 'Common', category: 'protein', flavorProfile: 'neutral', isPlural: false, suitability: ['steam', 'stir-fry', 'curry', 'bake', 'salad', 'dumpling'], description: 'Versatile soybean curd that absorbs the flavors of any dish.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Cabbage': 7, 'Oyster Mushrooms': 5, 'Shiitake Mushrooms': 6, 'Bean Sprouts': 4 } },
    { name: 'Mung Beans', emoji: '🫘', rarity: 'Common', category: 'protein', flavorProfile: 'savory', isPlural: true, suitability: ['curry', 'salad', 'steam'], description: 'Small, nutritious legumes that sprout easily and provide essential protein.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Lentils of the Four Winds', emoji: '🫘', rarity: 'Common', category: 'protein', flavorProfile: 'savory', isPlural: true, suitability: ['curry', 'bake', 'pie'], description: 'Sacred legumes said to be blessed by the four winds, providing strength and wisdom.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Temple Nuts', emoji: '🌰', rarity: 'Common', category: 'protein', flavorProfile: 'savory', isPlural: true, suitability: ['salad', 'bake', 'garnish'], description: 'Nuts harvested from the sacred trees surrounding Air Nomad temples.', nation: 'air-nomads', location: 'Air Temple' },
    
    // --- FLAVORING ---
    { name: 'Garlic', emoji: '🧄', rarity: 'Common', category: 'flavoring', flavorProfile: 'pungent', isPlural: false, suitability: ['steam', 'stir-fry', 'curry', 'bake', 'pie', 'dumpling'], description: 'A pungent bulb that adds depth and character to any dish.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Ginger', emoji: '🫚', rarity: 'Common', category: 'flavoring', flavorProfile: 'pungent', isPlural: false, suitability: ['steam', 'stir-fry', 'curry', 'bake', 'pie', 'dumpling', 'juice'], description: 'A warming root that adds spice and aids digestion, valued for its medicinal properties.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Vanilla', emoji: '🍦', rarity: 'Rare', category: 'flavoring', flavorProfile: 'sweet', isPlural: false, suitability: ['bake', 'pie', 'juice'], description: 'A rare, aromatic spice that adds subtle sweetness and complexity to desserts.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Banana': 5, 'Moon Peach': 7 } },
    { name: "Monk's Honey", emoji: '🍯', rarity: 'Uncommon', category: 'flavoring', flavorProfile: 'sweet', isPlural: false, suitability: ['bake', 'pie', 'juice', 'garnish'], description: 'Pure honey collected by Air Nomad monks, said to contain the essence of mountain flowers.', nation: 'air-nomads', location: 'Air Temple', synergies: { 'Apple': 5, 'Lychee Nuts': 5, 'Moon Peach': 5 } },
    { name: 'Bird\'s Eye Chili', emoji: '🌶️', rarity: 'Rare', category: 'flavoring', flavorProfile: 'pungent', isPlural: false, suitability: ['curry', 'stir-fry'], description: 'A tiny, fiery chili that adds intense heat, used sparingly by the brave.', nation: 'air-nomads', location: 'Air Temple' },

    // --- NEW BEVERAGE & SALAD INGREDIENTS ---
    { name: 'Ginseng', emoji: '🌿', rarity: 'Uncommon', category: 'flavoring', flavorProfile: 'pungent', isPlural: false, suitability: ['beverage', 'soup-stew'], description: 'A powerful root known for its rejuvenating properties, often brewed into a stimulating tea.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Jasmine Flowers', emoji: '🌸', rarity: 'Uncommon', category: 'garnish', flavorProfile: 'sweet', isPlural: true, suitability: ['beverage', 'garnish', 'salad'], description: 'Fragrant blossoms used to infuse teas and desserts with a delicate, floral aroma.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Sky-Lemon', emoji: '🍋', rarity: 'Common', category: 'fruit', flavorProfile: 'savory', isPlural: false, suitability: ['beverage', 'salad', 'garnish'], description: 'A citrus fruit with a tart, refreshing flavor, grown in the sunny courtyards of the Air Temples.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Windflower Nectar', emoji: '💧', rarity: 'Rare', category: 'flavoring', flavorProfile: 'sweet', isPlural: false, suitability: ['beverage', 'dessert'], description: 'A sweet, ambrosial liquid collected from the rare Windflower, perfect for sweetening drinks.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Cloud-Top Mint', emoji: '🍃', rarity: 'Common', category: 'garnish', flavorProfile: 'pungent', isPlural: false, suitability: ['beverage', 'salad', 'garnish'], description: 'A variety of mint that grows only at high altitudes, known for its crisp, cooling taste.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Steamed Kale', emoji: '🥬', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: false, suitability: ['salad', 'side-dish', 'steam'], description: 'Hardy green leaves, lightly steamed to soften their texture while retaining nutrients. A staple in meditative meals.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Sun-Dried Tomatoes', emoji: '🍅', rarity: 'Uncommon', category: 'vegetable', flavorProfile: 'umami', isPlural: true, suitability: ['salad', 'bake', 'garnish'], description: 'Tomatoes dried in the mountain sun, concentrating their sweet and savory flavors.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Toasted Sesame Seeds', emoji: '🌰', rarity: 'Common', category: 'garnish', flavorProfile: 'savory', isPlural: true, suitability: ['salad', 'garnish', 'stir-fry'], description: 'Seeds toasted to bring out their nutty, rich flavor, often sprinkled over salads and noodle dishes.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Avocado', emoji: '🥑', rarity: 'Uncommon', category: 'fruit', flavorProfile: 'savory', isPlural: false, suitability: ['salad', 'snack', 'beverage'], description: 'A creamy, rich fruit that adds a smooth texture to salads and nutrient-dense smoothies.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Herbal Tea Leaves', emoji: '🫖', rarity: 'Common', category: 'flavoring', flavorProfile: 'neutral', isPlural: true, suitability: ['beverage'], description: 'A blend of calming herbs from the temple gardens, brewed into a meditative tea.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Dandelion Greens', emoji: '🌿', rarity: 'Common', category: 'vegetable', flavorProfile: 'pungent', isPlural: true, suitability: ['salad', 'steam'], description: 'Slightly bitter greens foraged from the mountainside, prized for their detoxifying properties.', nation: 'air-nomads', location: 'Air Temple' },
    { name: 'Cucumber', emoji: '🥒', rarity: 'Common', category: 'vegetable', flavorProfile: 'neutral', isPlural: false, suitability: ['salad', 'beverage'], description: 'A crisp, hydrating vegetable that adds a refreshing quality to salads and infused water.', nation: 'air-nomads', location: 'Air Temple' }
];