export const loadingQuotes: string[] = [
    "The spirits are cooking...",
    "Consulting the ancient recipes...",
    "Adding a dash of honor!",
    "Slicing cabbages... carefully.",
    "Waiting for the stew to simmer.",
    "Perfecting the tea blend.",
    "That's a sharp outfit, Chan. Careful, you could puncture the hull of an empire-class Fire Nation battle ship, leaving thousands to drown at sea... because it's so sharp.",
    "Tasting for poisonous fungi...",
    "My cabbages!!",
    "Harnessing the flame's energy.",
    "Balancing the flavors of the four nations.",
    "Is this... cactus juice?",
    "Secret tunnel! Through the mountain!",
]; 