import { Ingredient } from './types';

/**
 * Water Tribe ingredients reflect their maritime culture and harsh environment.
 * Includes sea creatures, tundra plants, and preservation techniques.
 */
export const waterTribeIngredients: Ingredient[] = [
    // --- PROTEIN (From the Sea) ---
    { name: 'Sea Prunes', emoji: '🐙', rarity: 'Common', category: 'protein', flavorProfile: 'savory', isPlural: true, suitability: ['stew', 'poach', 'boil'], description: 'A staple of the Southern Water Tribe, these small, tender cephalopods are a primary source of protein.', nation: 'water-tribe', location: 'Water Tribe', synergies: { 'Kelp': 7, 'Thick Blubber Broth': 10 } },
    { name: 'Arctic Hen', emoji: '🐧', rarity: 'Common', category: 'protein', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'grill'], description: 'A flightless bird whose meat is rich and hearty, perfect for warming stews.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Tiger Seal', emoji: '🦭', rarity: 'Uncommon', category: 'protein', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'grill', 'cure'], description: 'A prized catch, providing tough but flavorful meat that is often cured for long voyages.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Moon-gilled Salmon', emoji: '🐟', rarity: 'Rare', category: 'protein', flavorProfile: 'umami', isPlural: false, suitability: ['poach', 'grill'], description: 'A beautiful fish whose gills shimmer with moonlight, known for its delicate, buttery flavor.', nation: 'water-tribe', location: 'Water Tribe', synergies: { 'Glacier Mint': 8 }, loreSnippet: 'The Moon-gilled Salmon is said to swim only during the full moon, when its gills glow with an ethereal light that guides Waterbenders to the best fishing spots.' },
    { name: 'Glacier Shrimp', emoji: '🦐', rarity: 'Common', category: 'protein', flavorProfile: 'sweet', isPlural: true, suitability: ['poach', 'stew', 'boil'], description: 'Small, sweet shrimp found in the frigid waters beneath glaciers, sometimes dried into powder.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Giant Sea Crab', emoji: '🦀', rarity: 'Rare', category: 'protein', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'boil'], description: 'A delicacy of the Northern Water Tribe, considered by many to be the most sought-after food in the Northern Sea.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Platypus Bear', emoji: '🐻', rarity: 'Legendary', category: 'protein', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'grill'], description: 'An enormous and dangerous beast, served whole only at the grandest of Northern Water Tribe feasts.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Squid', emoji: '🦑', rarity: 'Common', category: 'protein', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'boil'], description: 'A common catch used in many popular soups and stews across both tribes.', nation: 'water-tribe', location: 'Water Tribe' },

    // --- VEGETABLES / FLORA (From the Tundra and Sea) ---
    { name: 'Kelp', emoji: '🌿', rarity: 'Common', category: 'vegetable', flavorProfile: 'umami', isPlural: false, suitability: ['poach', 'stew', 'boil', 'salad'], description: 'Versatile sea-vegetable used for noodles, wraps, and seasoning.', nation: 'water-tribe', location: 'Water Tribe', synergies: { 'Sea Prunes': 7 } },
    { name: 'Sea Salt Root', emoji: '🥔', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'grill', 'boil'], description: 'A starchy root vegetable that grows in coastal soil, naturally infused with a mild saltiness.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Tundra Berries', emoji: '🫐', rarity: 'Common', category: 'vegetable', flavorProfile: 'savory', isPlural: true, suitability: ['stew', 'garnish', 'cure'], description: 'Hardy, tart berries that add a burst of acidity to rich, savory stews.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Ice-crystal Lettuce', emoji: '🥬', rarity: 'Uncommon', category: 'vegetable', flavorProfile: 'neutral', isPlural: false, suitability: ['salad'], description: 'A crisp, pale lettuce that thrives in the cold, with a texture like biting into fresh snow.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Dandelion Greens', emoji: '🌱', rarity: 'Uncommon', category: 'vegetable', flavorProfile: 'savory', isPlural: true, suitability: ['garnish', 'salad'], description: 'Bitter greens used as a garnish to cut through the richness of blubber and fatty meats.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Taro Root', emoji: '🍠', rarity: 'Rare', category: 'vegetable', flavorProfile: 'sweet', isPlural: false, suitability: ['stew', 'boil', 'freeze'], description: 'A sweet, starchy root grown in the Spirit Oasis, used to make a paste for mooncakes.', nation: 'water-tribe', location: 'Water Tribe' },
    
    // --- BASE (The foundation of a meal) ---
    { name: 'Seaweed Noodles', emoji: '🍜', rarity: 'Common', category: 'base', flavorProfile: 'umami', isPlural: true, suitability: ['stew', 'boil', 'poach'], description: 'Slippery, savory noodles made from processed kelp, a staple in brothy dishes.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Pearl-grain Rice', emoji: '🍚', rarity: 'Uncommon', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['stew', 'poach', 'boil'], description: 'A short-grain, sticky rice traded from the Earth Kingdom, considered a luxury.', nation: 'water-tribe', location: 'Generic' },
    { name: 'Thick Blubber Broth', emoji: '🥣', rarity: 'Common', category: 'base', flavorProfile: 'savory', isPlural: false, suitability: ['stew', 'poach'], description: 'A rich, high-energy broth made from rendered seal blubber, essential for survival.', nation: 'water-tribe', location: 'Water Tribe', synergies: { 'Sea Prunes': 10 } },
    { name: 'Imported Flour', emoji: '🌾', rarity: 'Uncommon', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['bake'], description: 'A luxury from the Earth Kingdom, used to make special breads and cookies after the War.', nation: 'water-tribe', location: 'Generic' },

    // --- FRUIT & DESSERT ---
    { name: 'Snow Plums', emoji: '🍑', rarity: 'Common', category: 'fruit', flavorProfile: 'sweet', isPlural: true, suitability: ['freeze', 'brew'], description: 'Sweet, pale plums that have a unique, icy crunch when eaten raw.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Polar Berries', emoji: '🍓', rarity: 'Uncommon', category: 'fruit', flavorProfile: 'sweet', isPlural: true, suitability: ['freeze', 'brew'], description: 'Extremely sweet berries used to make frozen desserts and sweet drinks.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Arctic Cloudberries', emoji: '🫐', rarity: 'Rare', category: 'fruit', flavorProfile: 'sweet', isPlural: true, suitability: ['freeze', 'brew'], description: 'Golden-orange berries that grow close to the ground, prized for their unique tart-sweet flavor.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Sweetened Seal Milk', emoji: '🥛', rarity: 'Common', category: 'dairy', flavorProfile: 'sweet', isPlural: false, suitability: ['freeze', 'brew'], description: 'Rich, creamy milk used as the base for most Water Tribe frozen desserts.', nation: 'water-tribe', location: 'Water Tribe' },

    // --- FLAVORING & GARNISH ---
    { name: 'Glacier Salt', emoji: '🧂', rarity: 'Common', category: 'flavoring', flavorProfile: 'savory', isPlural: false, suitability: ['poach', 'stew', 'grill', 'cure', 'boil'], description: 'Coarse salt harvested from ancient glacial deposits.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Tundra Herbs', emoji: '🌿', rarity: 'Common', category: 'flavoring', flavorProfile: 'pungent', isPlural: true, suitability: ['stew', 'grill', 'cure'], description: 'A mix of hardy, aromatic herbs that grow on the sparse tundra.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Whale Oil', emoji: '💧', rarity: 'Common', category: 'flavoring', flavorProfile: 'umami', isPlural: false, suitability: ['grill', 'stew'], description: 'A rich, savory oil used for cooking and fueling lamps, defining the smoky taste of grilled foods.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Butterfly Pea Flower', emoji: '🌸', rarity: 'Legendary', category: 'flavoring', flavorProfile: 'sweet', isPlural: false, suitability: ['brew'], description: 'A rare flower from the Spirit Oasis, its extract is used in spiritual teas, turning them a beautiful blue.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Glacier Mint', emoji: '🍃', rarity: 'Uncommon', category: 'garnish', flavorProfile: 'sweet', isPlural: false, suitability: ['freeze', 'garnish', 'brew'], description: 'A potent mint that provides a cooling sensation, often used in drinks and desserts.', nation: 'water-tribe', location: 'Water Tribe', synergies: { 'Moon-gilled Salmon': 8 } },

    // --- NEW BEVERAGE & SALAD INGREDIENTS ---
    { name: 'Sea-Kelp Salad Base', emoji: '🥗', rarity: 'Common', category: 'vegetable', flavorProfile: 'umami', isPlural: false, suitability: ['salad'], description: 'A mix of tender, young kelp and other seaweeds, serving as a common base for chilled salads.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Pickled Sea Prunes', emoji: '🐙', rarity: 'Uncommon', category: 'protein', flavorProfile: 'savory', isPlural: true, suitability: ['salad', 'garnish'], description: 'Young sea prunes pickled in a salty brine, adding a chewy texture and savory flavor to salads.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Arctic Willow Leaves', emoji: '🌿', rarity: 'Common', category: 'vegetable', flavorProfile: 'pungent', isPlural: true, suitability: ['salad', 'beverage', 'stew'], description: 'The young leaves of the arctic willow, edible and slightly bitter, often used in salads or brewed as a tea.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Meltwater', emoji: '💧', rarity: 'Common', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['beverage', 'soup-stew'], description: 'Pure, clean water sourced directly from melting glaciers, the foundation of all Water Tribe beverages.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Iced Nectar', emoji: '🍹', rarity: 'Uncommon', category: 'flavoring', flavorProfile: 'sweet', isPlural: false, suitability: ['beverage'], description: 'A sweet, non-alcoholic drink made from a blend of polar berry juices, served ice-cold.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Spirit Oasis Water', emoji: '💧', rarity: 'Legendary', category: 'base', flavorProfile: 'neutral', isPlural: false, suitability: ['beverage', 'soup-stew'], description: 'Sacred water from the Spirit Oasis in the North Pole, said to have healing properties.', nation: 'water-tribe', location: 'Water Tribe', loreSnippet: 'The Spirit Oasis Water never freezes, even in the coldest winters, and is said to contain the essence of the Moon and Ocean spirits themselves.' },
    { name: 'Frozen Moss', emoji: '🧊', rarity: 'Common', category: 'vegetable', flavorProfile: 'neutral', isPlural: false, suitability: ['salad', 'garnish'], description: 'Edible tundra moss, flash-frozen with waterbending to create a crunchy, cold salad topping.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Sea-Ice Radish', emoji: '🌶️', rarity: 'Common', category: 'vegetable', flavorProfile: 'pungent', isPlural: false, suitability: ['salad', 'garnish'], description: 'A crisp, peppery radish that grows in the icy soil of the tundra, sliced thin for salads.', nation: 'water-tribe', location: 'Water Tribe' },
    { name: 'Blubber-Cured Fish', emoji: '🐟', rarity: 'Uncommon', category: 'protein', flavorProfile: 'umami', isPlural: false, suitability: ['salad', 'snack'], description: 'Fish cured and preserved in seal blubber, providing a rich, smoky flavor perfect for adding protein to a cold salad.', nation: 'water-tribe', location: 'Water Tribe' }
]; 